const words = [
    { kanji: "依然として", hira: "いぜんとして", kr: "여전히" },
  { kanji: "誤り", hira: "あやまり", kr: "잘못, 실수, 착오, 오류" },
  { kanji: "謝り", hira: "あやまり", kr: "사과" },
  { kanji: "言い訳", hira: "いいわけ", kr: "변명" },
  { kanji: "怒り", hira: "いかり", kr: "분노, 화" },
  { kanji: "勢い", hira: "いきおい", kr: "기세" },
  { kanji: "香り", hira: "かおり", kr: "향기" },
  { kanji: "飾り", hira: "かざり", kr: "장식" },
  { kanji: "好み", hira: "このみ", kr: "기호, 취향" },
  { kanji: "締め切り", hira: "しめきり", kr: "마감" },
  { kanji: "強み", hira: "つよみ", kr: "강점" },
  { kanji: "手応え", hira: "てごたえ", kr: "보람" },
  { kanji: "手続き", hira: "てつづき", kr: "수속" },
  { kanji: "仲直り", hira: "なかなおり", kr: "화해" },
  { kanji: "半ば", hira: "なかば", kr: "절반" },
  { kanji: "望み", hira: "のぞみ", kr: "바람, 소망" },
  { kanji: "人込み", hira: "ひとごみ", kr: "인파, 붐빔" },
  { kanji: "誇り", hira: "ほこり", kr: "자랑, 긍지" },
  { kanji: "催し", hira: "もよおし", kr: "개최" },
  { kanji: "最寄り", hira: "もより", kr: "근처, 가장 가까움" },
  { kanji: "世の中", hira: "よのなか", kr: "세상" },
  { kanji: "腕", hira: "うで", kr: "팔, 솜씨" },
  { kanji: "鍵", hira: "かぎ", kr: "열쇠" },
  { kanji: "粉", hira: "こな", kr: "가루" },
  { kanji: "印", hira: "しるし", kr: "표시" },
  { kanji: "姿", hira: "すがた", kr: "모습" },
  { kanji: "隅", hira: "すみ", kr: "구석" },
  { kanji: "袖", hira: "そで", kr: "소매" },
  { kanji: "縦", hira: "たて", kr: "세로" },
  { kanji: "横", hira: "よこ", kr: "가로, 옆" },
  { kanji: "束", hira: "たば", kr: "다발, 묶음" },
  { kanji: "旅", hira: "たび", kr: "여행" },
  { kanji: "立派だ", hira: "りっぱだ", kr: "훌륭하다" },
  { kanji: "盛んだ", hira: "さかんだ", kr: "번창하다" },
  { kanji: "賑やかだ", hira: "にぎやかだ", kr: "번화하다" },
  { kanji: "派手だ", hira: "はでだ", kr: "화려하다" },
  { kanji: "華やかだ", hira: "はなやかだ", kr: "화려하다" },
  { kanji: "居眠り", hira: "いねむり", kr: "앉아서 졺" },
  { kanji: "しっとりだ", hira: "しっとりだ", kr: "촉촉하다" },
  { kanji: "荒れる", hira: "あれる", kr: "거칠어지다" },
  { kanji: "きれいだ", hira: "きれいだ", kr: "예쁘다" },
  { kanji: "汚い", hira: "きたない", kr: "더럽다" },
  { kanji: "量が多い", hira: "りょうがおおい", kr: "양이 많다" },
  { kanji: "おかしな", hira: "おかしな", kr: "이상한" },
  { kanji: "不安な", hira: "ふあんな", kr: "불안한" },
  { kanji: "退屈な", hira: "たいくつな", kr: "지루한" },
  { kanji: "かわいそうな", hira: "かわいそうな", kr: "불쌍한" },
  { kanji: "しきりに", hira: "しきりに", kr: "자주" },
  { kanji: "無理やりに", hira: "むりやりに", kr: "무리하게" },
  { kanji: "おのおの", hira: "おのおの", kr: "각각" },
  { kanji: "あいにく", hira: "あいにく", kr: "공교롭게도" },
  { kanji: "強いて", hira: "しいて", kr: "억지로" },
  { kanji: "上達", hira: "じょうたつ", kr: "실력 향상" },
  { kanji: "比較", hira: "ひかく", kr: "비교" },
  { kanji: "悪影響", hira: "あくえいきょう", kr: "악영향" },
  { kanji: "悪条件", hira: "あくじょうけん", kr: "악조건" },
  { kanji: "アメリカ流", hira: "あめりかりゅう", kr: "미국식" },
  { kanji: "アルファベット順", hira: "あるふぁべっとじゅん", kr: "알파벳순" },
  { kanji: "医学界", hira: "いがくかい", kr: "의학계" },
  { kanji: "一日おきに", hira: "いちにちおきに", kr: "하루 걸러" },
  { kanji: "異文化", hira: "いぶんか", kr: "이문화" },
  { kanji: "異分野", hira: "いぶんや", kr: "이분야, 다른 분야" },
  { kanji: "薄暗い", hira: "うすぐらい", kr: "좀 어둡다, 침침하다" },
  { kanji: "応援団", hira: "おうえんだん", kr: "응원단" },
  { kanji: "親子連れ", hira: "おやこずれ", kr: "부모와 자녀 동반" },
  { kanji: "音楽全般", hira: "おんがくぜんぱん", kr: "음악 전반" },
];
